name: flutter_weather_demo
publish_to: none
description: Demo project for flutter_command .
version: 1.0.0+1
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.0
  flutter_command: 
    path: ../
  functional_listener: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
