name: flutter_weather_demo
description: Example for flutter_command that uses CommandResults
version: 1.0.0+1
environment:
  sdk: '>=2.18.0 <3.0.0'

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.0
  flutter_command: 
    path: ../
  functional_listener: ^2.3.1

flutter:
  uses-material-design: true
